# Generated by Django 3.2.7 on 2022-03-05 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workout_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutmenu',
            name='date_of_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
